# enviroment setups for back-end operation
name: app-books
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pyzbar
  - google-api-python-client
  - django==4.1.4
  - djangorestframework==3.14.0
  - pillow
  - pip:
      - opencv-python==4.9.0.80