# Generated by Django 4.1.4 on 2024-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getBookData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='publisher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookdata',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
